server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    orderEventTopic: "order-topic"
    orderStatusEventTopic: "order-status-topic"
    kafkaEventGroupId: "order-event-group-id"